# https://medium.com/javascript-in-plain-english/publish-update-npm-packages-with-github-actions-e4d786ffd62a
name: 'Commit tests'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@buccaneerai'
          always-auth: true
      - name: Setup .env file
        run: cp local.env .env
      - name: Install packages
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Run tests
        run: yarn test
        env:
          START_SERVER: 'false'
          SUPPRESS_LOGS: '1'
      - name: Run Linter
        run: yarn lint
      - name: Build
        run: yarn build
